[main]
font=CaskaydiaCove Nerd Font:size=13
prompt=❯
width=35
lines=15
inner-pad=12
line-height=24
minimal-lines=yes

[colors]
# Everblush
background=141B1Eee
text=DADADAff
prompt=B3B9B8ff
input=DADADAff
match=8CCF7Eff
selection=232A2Dff
selection-text=DADADAff
selection-match=96D988ff
border=C47FD5ff

[border]
width=2
radius=12
