tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "fish"
brew "handbrake"
brew "mas"
brew "rcm"
cask "appcleaner"
cask "daisydisk"
cask "discord"
cask "figma"
cask "font-hack"
cask "github"
cask "google-chrome"
cask "imageoptim"
cask "iterm2"
cask "keyboardcleantool"
cask "linear-linear"
cask "noun-project"
cask "raycast"
cask "rectangle"
cask "rider"
cask "slack"
cask "spotify"
cask "superhuman"
cask "unity-hub"
cask "visual-studio-code"
cask "zoom"
mas "Gifski", id: 1351639930
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "Xcode", id: 497799835
