" Use Vim defaults, not Vi's.
set nocompatible

" Because not everybody's a hipster
if &shell =~# 'fish$'
    set shell=sh
endif

" Store viminfo inside vim folder (vim 7.4 rocks #bless)
set viminfo+=n~/.vim/viminfo

" Kill swapfiles with fire
set noswapfile
set nobackup
set nowb

" BASH-like autocompletion
set wildmode=longest:full
set wildmenu

" Allow backspace in insert mode
set backspace=indent,eol,start

" Highlight search things
set incsearch       " Find the next match as we type the search
set hlsearch        " Highlight searches by default
set ignorecase      " Ignore case when searching...
set smartcase       " ...unless we type a capital

" Wrapping
set nowrap       "Don't wrap lines
set linebreak    "Wrap lines at convenient points

" Scrolling
set scrolloff=8
set sidescrolloff=15
set sidescroll=1

" Bash like keys for the command line
cnoremap <C-A>      <Home>
cnoremap <C-E>      <End>

" Line numbers
set number

" Sync X and Vim clipboards
set clipboard=unnamed

" Show the filename in the titlebar, don't set 'Thanks for flying' message
set title
let &titleold=''

" Don't show the intro message when starting Vim
set shortmess=atI

" Mouse support
set mouse=a

" Dynamic cursor shape (block/beam/underline)
let &t_SI = "\e[6 q"  " insert mode: beam |
let &t_EI = "\e[2 q"  " normal mode: block
let &t_SR = "\e[4 q"  " replace mode: underline

" Colors
syntax on

" Folding
set nofoldenable
set foldmethod=indent
set foldnestmax=3
set foldlevel=1
nnoremap <space> za
vnoremap <space> zf

" Automatically based on previous line
set autoindent

" re-open file to last line
if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
