# Do not modify this file!  It was generated by ‘nixos-generate-config’
# t
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [
    # Workaround: disable VPE (Video Processing Engine) IP block to prevent
    # s2idle suspend hard-hang. vpe_v6_1 fails to quiesce during s2idle on
    # RDNA 3.5 — the VPE queue reset times out on resume ("IB test failed on
    # vpe (-110)"), and a subsequent suspend freezes the SoC entirely (no panic,
    # no log, requires hard power-off).
    # VPE handles video scaling/color offload and is non-essential.
    # Bit 11 = vpe_v6_1 on this ASIC (indices vary per ASIC; verify with
    #   `journalctl -k | grep "detected ip block"`).
    # Bug: https://bugzilla.kernel.org/show_bug.cgi?id=220812
    # Patch: https://lore.kernel.org/amd-gfx/20251130014631.29755-1-superm1@kernel.org/
    # AMD says the fix comes via SoC firmware in a BIOS update, NOT the kernel:
    # the in-kernel workaround (commit 31ab31433c "skip power ungate during
    # suspend for VPE") was reverted upstream and the revert is in 7.1.
    #
    # Release condition: drop this + re-enable VPE once a BIOS bumps the AMD PI
    # version past StrixKrackanPI-FP8 1.1.0.2d and survives several suspend
    # cycles. Checked 2026-07-27 — NOT met. BIOS 4.01 (2026-07-06) is out and
    # fwupd offers it, but ships the same 1.1.0.2d as 3.05 and 3.06; its
    # changelog is a dGPU BOCO power-limit fix, an NVIDIA G-Sync key and BIOS
    # menu rendering, and it carries a known issue of "intermittent CPU
    # frequency lock at 600 MHz following S3/Modern Standby resume" — so it is
    # not worth taking on a machine that suspends constantly.
    # AMD PI version is on each release page, not the index:
    #   https://resources.frame.work/downloads/laptop-16/amd-ryzen-ai-300-series/4.01/
    # Mainline amdgpu_vpe.c has no v6.1 fix either (verified same day; the only
    # change since 7.1.4 is new VPE 2.0 hardware support).
    "amdgpu.ip_block_mask=0xFFFFF7FF"

    # Log ACPI LPS0 constraint failures during s2idle to dmesg. Needed to
    # diagnose why amd_pmc never reaches the deepest S0i3 state.
    # Check after resume: journalctl -k | grep -i 'constraint\|LPI\|acpi.*pm'
    # Remove once s0ix is fixed.
    "pm_debug_messages"

    # Resume from hibernate (swap file on root ext4).
    # Offset found via: sudo filefrag -v /swapfile | awk '$1=="0:"{print $4}'
    "resume_offset=225771520"

    # Switch PREEMPT_DYNAMIC from "voluntary" (NixOS default) to "full".
    # Adds preemption points on more kernel-return paths, shortening worst-case
    # non-preemptible regions during heavy fs/mm syscalls (the proximate cause
    # of "cursor froze for ¼ sec" during big writes). Throughput cost is
    # single-digit % on syscall-heavy benchmarks, invisible interactively.
    "preempt=full"

    # Re-enable scatter/gather display, overriding nixos-hardware's
    # `amdgpu.sg_display=0` for the FW16 AI 300 module.
    #
    # The nixos-hardware default came in via copy-paste from a config written
    # for FW16 Phoenix/DCN 3.1.4 (lbrame's gist), where it was a "last-ditch"
    # workaround for flicker/white-frame bugs. Those bugs were on DCN 2.1.0
    # through DCN 3.1.5 silicon — this machine is DCN 3.5 (Krackan Point), a
    # different display block that the original bug never affected. Mario
    # Limonciello (AMD upstream amdgpu maintainer) has explicitly told AI 300
    # users to drop sg_display=0 in Framework community discussion.
    # nixos-hardware itself removed the equivalent workaround for Raphael
    # iGPU on kernel 6.6+ in PR #980; the AI 300 module is leftover scaffolding.
    #
    # Keeping sg_display=0 forced every display framebuffer to be pinned in
    # the 512 MB contiguous UMA VRAM carveout. Hotplugging a 4K external on
    # the TS4/TS3 dock would intermittently fail to pin (-ENOMEM), cascading
    # into DPIA AUX failure and a wedged DP-over-USB4 tunnel. Per AMD, S/G
    # off causes "frame-buffer errors and blank displays when under memory
    # pressure" — which is the TS4-wedge bug we've been hitting.
    #
    # Linux kernel module params: when the same key appears multiple times on
    # the cmdline, the last one wins (already exercised by our existing
    # `amdgpu.dcdebugmask=0x10 amdgpu.dcdebugmask=0x410`). So appending =1
    # here overrides the =0 contributed by the nixos-hardware module without
    # needing to filter or mkForce its kernelParams list. Verify with
    # `cat /proc/cmdline | tr ' ' '\n' | grep sg_display` — should show both,
    # the last one being =1.
    #
    # Discussion:
    #   - nixos-hardware PR #980 (Raphael sg_display dropped on kernel 6.6+)
    #   - Framework community thread: AMD GPU MES Timeouts on FW13 AI 300
    #
    # Upstream check 2026-07-27: nixos-hardware master still ships
    # `amdgpu.sg_display=0` (plus dcdebugmask=0x410 and abmlevel=0) in
    # framework/16-inch/amd-ai-300-series/default.nix, so this override is
    # still needed. Worth upstreaming as a PR at some point — the same
    # reasoning applies to abmlevel=0, which we currently inherit unexamined
    # and which costs backlight power savings.
    "amdgpu.sg_display=1"

    # Block IPS2 while keeping Panel Self Refresh and Panel Replay. Overrides
    # nixos-hardware's `amdgpu.dcdebugmask=0x10` (framework/16-inch/common/amd.nix)
    # and `=0x410` (amd-ai-300-series).
    #
    # Bit layout, verified 2026-07-27 against enum DC_DEBUG_MASK in
    # drivers/gpu/drm/amd/include/amd_shared.h. An earlier version of this comment
    # had 0x400 wrong — do not trust it from memory, it is easy to misread:
    #   0x0010 = DC_DISABLE_PSR            (Panel Self Refresh)
    #   0x0400 = DC_DISABLE_REPLAY         (Panel Replay) — NOT an IPS bit
    #   0x0800 = DC_DISABLE_IPS            (all IPS, including during suspend)
    #   0x1000 = DC_DISABLE_IPS_DYNAMIC    (IPS at runtime; still allowed in suspend)
    #   0x2000 = DC_DISABLE_IPS2_DYNAMIC   (IPS2 only, while displays are enabled)
    #
    # PSR and Replay let the panel refresh itself from its own framebuffer when no
    # new content is produced, so the display engine and eDP link can drop into
    # deep power-save. Worth ~1-2 hours of idle battery here. The nixos-hardware
    # modules disable both over historical hang/flicker bugs on Phoenix-era
    # (DCN 3.1.x) silicon.
    #
    # 2026-05-16 (ddb8cf6) we set =0x0 to test whether that was still needed on
    # DCN 3.5. Note what =0x0 actually did: it enabled PSR and Replay. It did NOT
    # "re-enable IPS2" — no dcdebugmask value in play ever touched IPS, so IPS has
    # been enabled the whole time, before and after. Verdict after ~10 weeks:
    #
    #   2026-05-19 15:27  7.0.8  WARN dc_dmub_srv.c:1698, recovered
    #   2026-07-25 00:07  7.1.0  WARN dc_dmub_srv.c:1705, recovered
    #   2026-07-27 00:05  7.1.4  no warn — hard hang, power-cycle required
    #
    # The hang: a scanout-position query inside amdgpu_dm_atomic_commit_tail
    # (via drm_vblank_get -> drm_update_vblank_count) reaches
    # dc_allow_idle_optimizations_internal -> dcn35_apply_idle_power_optimizations
    # -> dc_dmub_srv_notify_idle, which busy-waits in dmub_srv_wait_for_idle for a
    # DMCUB ack that never arrives. That worker owns every display commit, so the
    # compositor dies with it: RCU stall on CPU 0, GPU fences stop signalling,
    # then soft lockup. amdgpu has no recovery path for a wedged display block the
    # way it does for a hung ring — the machine is gone until power-cycled.
    #
    # Why enabling PSR/Replay lit up an IPS bug: they are the precondition for
    # deep idle. Without panel self-refresh the display engine must keep scanning
    # out, DCN never reaches deep idle, and IPS2 is unreachable in practice. Turn
    # PSR/Replay on and the IPS2 entry path becomes live for the first time.
    # Upstream states plainly that "any DCN programming while we're in IPS leads
    # to undefined behavior (mostly hangs)" — DC is supposed to exit IPS before
    # touching DCN registers, and here that exit handshake is what deadlocked.
    #
    # Not the dock: internal eDP-1 only, no external display, no TBT activity.
    # Both midnight hits landed ~5 min after the nix-gc timer fires at 00:00,
    # consistent with a wakeup racing IPS2 entry while the panel sits idle.
    #
    # So: 0x2000 blocks IPS2 while displays are on, and leaves PSR and Replay
    # enabled so the battery win survives. IPS1 entry stays live, so this is
    # targeted rather than airtight.
    #
    # Escalate, in order, if freezes continue:
    #   0x1000 — kill IPS at runtime too, but keep it during suspend so s0ix works
    #   (drop this line) — back to nixos-hardware 0x410; proven stable pre-2026-05-16,
    #                      but gives up PSR/Replay and the idle battery win
    # Avoid 0x800: it disables IPS during suspend as well and can cost s0ix.
    # Detect a recurrence with (note -k implies current boot only):
    #   journalctl _TRANSPORT=kernel | grep dcn35_apply_idle_power_optimizations
    "amdgpu.dcdebugmask=0x2000"

    # Disable the kernel TBT/USB4 host-router reset performed during driver
    # probe. Default is `true` (added by AMD in 6.6.29 / 6.8.8 via Sanath S's
    # quirk for Yellow Carp / Pink Sardine FCH lineage — Strix Point inherits
    # the same firmware behavior). The reset throws away the BIOS's PCIe bus
    # allocation for TBT downstream ports so the kernel can re-allocate with
    # headroom for deep daisy chains; we don't daisy-chain (TS4 is the only
    # TBT device), so we get none of the benefit and all of the regression
    # risk: AMD + TBT4 docks routinely fail to re-create USB tunnels after
    # the reset, and on this machine an xHCI HC death during a live TBT
    # replug left the keyboard (which shares controller 0000:c5:00.0 with
    # the TBT port) wedged until a manual `xhci_hcd` unbind/bind.
    #
    # Trade-off: with =0 we cap at the firmware's bus allocation (fine for
    # single-device TBT use); we gain stability for the TS4 USB tunnel and
    # the keyboard-survives-TBT-events case.
    #
    # Revert: remove this line. Verify current state with
    #   cat /sys/module/thunderbolt/parameters/host_reset   # Y or N
    #
    # Upstream check 2026-07-27: drivers/thunderbolt/nhi.c in mainline still
    # has `static bool host_reset = true;` — no default flip, no quirk for
    # AMD/Strix, so this override is still doing work.
    #
    # Refs:
    #   - Patch (AMD): https://lists.openwall.net/linux-kernel/2023/11/22/161
    #   - Regression (Dell WD19TB, leading to the parameter):
    #     https://www.spinics.net/lists/linux-usb/msg262200.html
    #   - Framework workaround thread:
    #     https://community.frame.work/t/workaround-xhci-host-controller-not-responding-at-resume-after-suspend/79119
    "thunderbolt.host_reset=0"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7275aed4-0266-4f84-8169-246b245640f9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7275aed4-0266-4f84-8169-246b245640f9".device = "/dev/disk/by-uuid/7275aed4-0266-4f84-8169-246b245640f9";

  # Resume from hibernate — the root LUKS device contains the swap file.
  boot.resumeDevice = "/dev/mapper/luks-7275aed4-0266-4f84-8169-246b245640f9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AA80-84F8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  zramSwap = {
    enable = true;
    # 75% (≈23 GiB logical) up from the 50% default. This box runs a chronically
    # over-committed working set (Chrome + multiple GiB-scale terminals + LLM CLIs
    # + Rust builds), so it lives deep in swap. At 50% (15 GiB) zram fills and the
    # tail spills to the slow disk /swapfile (prio -1), and faulting interactive
    # threads block on that disk I/O — observed as UI lag (user.slice io.pressure
    # full ~63% during builds, while CPU full-pressure stayed 0: this is a memory,
    # not a scheduling, problem).
    #
    # memoryPercent sets the *logical (uncompressed)* device size, not a
    # compression promise. Physical RAM cost = stored ÷ ratio; at the observed
    # ~4.5:1 zstd ratio, a full 23 GiB device costs only ~5 GiB physical, which
    # comfortably holds the current ~23 GiB swapped set in RAM instead of on disk.
    #
    # Not 100%: zram (prio 5) fills before the disk swapfile, and a full device's
    # worst-case (incompressible, ~1:1) cost would consume all RAM and OOM before
    # ever spilling to disk. 75% keeps a survivable working-set floor if the ratio
    # degrades and preserves the disk swapfile as a genuine last-resort valve.
    memoryPercent = 75;
  };

  # Optimize sysctl parameters for zram swap.
  #
  # With zram, "swapping" means compressing pages in RAM rather than writing
  # to disk, so the cost/benefit tradeoffs of these tunables change significantly.
  #
  # References:
  #   - https://wiki.archlinux.org/title/Zram#Optimizing_swap_on_zram
  #   - https://docs.kernel.org/admin-guide/sysctl/vm.html
  #   - https://github.com/NixOS/nixpkgs/pull/351002
  boot.kernel.sysctl = {
    # NixOS default is 16 (remount only). Enable all SysRq functions so
    # Alt+SysRq+REISUB can recover from kernel deadlocks and hangs.
    "kernel.sysrq" = 1;
    # Default is 60. Range is 0-200 (expanded from 0-100 for zram/zswap).
    # Higher values tell the kernel to prefer compressing cold anonymous pages
    # into zram over evicting file cache. Since zram decompression (~µs) is
    # orders of magnitude faster than even NVMe reads (~100µs), this keeps
    # more hot file cache in RAM at the cost of cheap compression CPU cycles.
    "vm.swappiness" = 180;

    # Default is 15000. Controls reclaim of watermark_boost pages after an
    # external fragmentation event. Not useful with zram (no disk seek penalty
    # to amortize), and the wakeups waste power on laptops.
    "vm.watermark_boost_factor" = 0;

    # Default is 10 (0.1% of RAM). Distance between min/low/high watermarks.
    # Higher value gives kswapd more runway to reclaim in the background before
    # direct reclaim stalls occur, reducing latency spikes under pressure.
    "vm.watermark_scale_factor" = 125;

    # Default is 3 (read 2^3=8 pages at a time from swap). Swap readahead
    # helps with sequential disk access but zram has no seek penalty, so
    # readahead just wastes memory bandwidth. 0 disables it.
    "vm.page-cluster" = 0;
  };

  # Disk-backed swap for hibernate. zram handles day-to-day swapping (fast,
  # in-RAM compression) but can't persist across power-off. This file is only
  # used as the hibernate image target for suspend-then-hibernate.
  swapDevices = [{
    device = "/swapfile";
    size = 32 * 1024;  # 32 GiB (match RAM for hibernate)
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
