# Do not modify this file!  It was generated by ‘nixos-generate-config’
# t
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [
    # Workaround: disable VPE (Video Processing Engine) IP block to prevent
    # s2idle suspend hard-hang. vpe_v6_1 fails to quiesce during s2idle on
    # RDNA 3.5 — the VPE queue reset times out on resume ("IB test failed on
    # vpe (-110)"), and a subsequent suspend freezes the SoC entirely (no panic,
    # no log, requires hard power-off).
    # VPE handles video scaling/color offload and is non-essential.
    # Bit 11 = vpe_v6_1 on this ASIC (indices vary per ASIC; verify with
    #   `journalctl -k | grep "detected ip block"`).
    # Bug: https://bugzilla.kernel.org/show_bug.cgi?id=220812
    # Patch: https://lore.kernel.org/amd-gfx/20251130014631.29755-1-superm1@kernel.org/
    # AMD says the underlying fix will come in a BIOS update (BIOS 03.04 does
    # not include it yet). Remove this once a fixed BIOS ships for FW16 AI 300.
    "amdgpu.ip_block_mask=0xFFFFF7FF"

    # Log ACPI LPS0 constraint failures during s2idle to dmesg. Needed to
    # diagnose why amd_pmc never reaches the deepest S0i3 state.
    # Check after resume: journalctl -k | grep -i 'constraint\|LPI\|acpi.*pm'
    # Remove once s0ix is fixed.
    "pm_debug_messages"

    # Resume from hibernate (swap file on root ext4).
    # Offset found via: sudo filefrag -v /swapfile | awk '$1=="0:"{print $4}'
    "resume_offset=225771520"

    # Switch PREEMPT_DYNAMIC from "voluntary" (NixOS default) to "full".
    # Adds preemption points on more kernel-return paths, shortening worst-case
    # non-preemptible regions during heavy fs/mm syscalls (the proximate cause
    # of "cursor froze for ¼ sec" during big writes). Throughput cost is
    # single-digit % on syscall-heavy benchmarks, invisible interactively.
    "preempt=full"

    # Re-enable scatter/gather display, overriding nixos-hardware's
    # `amdgpu.sg_display=0` for the FW16 AI 300 module.
    #
    # The nixos-hardware default came in via copy-paste from a config written
    # for FW16 Phoenix/DCN 3.1.4 (lbrame's gist), where it was a "last-ditch"
    # workaround for flicker/white-frame bugs. Those bugs were on DCN 2.1.0
    # through DCN 3.1.5 silicon — this machine is DCN 3.5 (Krackan Point), a
    # different display block that the original bug never affected. Mario
    # Limonciello (AMD upstream amdgpu maintainer) has explicitly told AI 300
    # users to drop sg_display=0 in Framework community discussion.
    # nixos-hardware itself removed the equivalent workaround for Raphael
    # iGPU on kernel 6.6+ in PR #980; the AI 300 module is leftover scaffolding.
    #
    # Keeping sg_display=0 forced every display framebuffer to be pinned in
    # the 512 MB contiguous UMA VRAM carveout. Hotplugging a 4K external on
    # the TS4/TS3 dock would intermittently fail to pin (-ENOMEM), cascading
    # into DPIA AUX failure and a wedged DP-over-USB4 tunnel. Per AMD, S/G
    # off causes "frame-buffer errors and blank displays when under memory
    # pressure" — which is the TS4-wedge bug we've been hitting.
    #
    # Linux kernel module params: when the same key appears multiple times on
    # the cmdline, the last one wins (already exercised by our existing
    # `amdgpu.dcdebugmask=0x10 amdgpu.dcdebugmask=0x410`). So appending =1
    # here overrides the =0 contributed by the nixos-hardware module without
    # needing to filter or mkForce its kernelParams list. Verify with
    # `cat /proc/cmdline | tr ' ' '\n' | grep sg_display` — should show both,
    # the last one being =1.
    #
    # Discussion:
    #   - nixos-hardware PR #980 (Raphael sg_display dropped on kernel 6.6+)
    #   - Framework community thread: AMD GPU MES Timeouts on FW13 AI 300
    "amdgpu.sg_display=1"

    # Re-enable Panel Self Refresh and IPS2 Dynamic, overriding nixos-hardware's
    # `amdgpu.dcdebugmask=0x10` (from framework/16-inch/common/amd.nix, disables
    # PSR) and `=0x410` (from amd-ai-300-series, adds DC_DISABLE_IPS2_DYNAMIC).
    #
    # Bit layout:
    #   0x010 = DC_DISABLE_PSR        (Panel Self Refresh)
    #   0x400 = DC_DISABLE_IPS2_DYNAMIC
    #   0x000 = restore defaults (PSR and IPS2 dynamic both enabled)
    #
    # PSR lets the panel refresh itself from its internal framebuffer when no
    # new content is being produced, letting the GPU display engine and eDP
    # link drop into deep power-save states. Worth ~1-2 hours of idle battery
    # on this hardware. Disabled by the nixos-hardware modules because of
    # historical hang/flicker bugs on Phoenix-era (DCN 3.1.x) silicon.
    #
    # On DCN 3.5 (Krackan Point) with kernel 7.0.8 and recent DMUB firmware,
    # the situation has improved: nixos-hardware contributors are debating
    # whether to keep this workaround on by default (PR #1692). One tester
    # reported "removed it, latest kernel works fine"; another (a maintainer)
    # said dcdebugmask=0x410 was still load-bearing. Bug is intermittent
    # enough that only empirical testing on this specific machine can settle
    # it. We test by re-enabling and watching for symptoms.
    #
    # Watch for (would indicate keeping it on is still needed):
    #   - Random whole-system freezes where the cursor still moves but
    #     everything else is unresponsive — the FW13 AI 300 PSR signature
    #     (FrameworkComputer/SoftwareFirmwareIssueTracker#110)
    #   - Display flicker on light backgrounds, especially in browsers
    #   - Janky first frame after a period of idle (PSR exit glitch)
    #   - Black/white frames briefly during transitions
    #
    # Revert: just remove this line (nixos-hardware's 0x410 takes over again).
    # Bisect: if symptoms appear, try 0x400 to re-enable PSR but keep IPS2
    # dynamic disabled, to learn which half of the bitmask is problematic.
    "amdgpu.dcdebugmask=0x0"

    # Disable the kernel TBT/USB4 host-router reset performed during driver
    # probe. Default is `true` (added by AMD in 6.6.29 / 6.8.8 via Sanath S's
    # quirk for Yellow Carp / Pink Sardine FCH lineage — Strix Point inherits
    # the same firmware behavior). The reset throws away the BIOS's PCIe bus
    # allocation for TBT downstream ports so the kernel can re-allocate with
    # headroom for deep daisy chains; we don't daisy-chain (TS4 is the only
    # TBT device), so we get none of the benefit and all of the regression
    # risk: AMD + TBT4 docks routinely fail to re-create USB tunnels after
    # the reset, and on this machine an xHCI HC death during a live TBT
    # replug left the keyboard (which shares controller 0000:c5:00.0 with
    # the TBT port) wedged until a manual `xhci_hcd` unbind/bind.
    #
    # Trade-off: with =0 we cap at the firmware's bus allocation (fine for
    # single-device TBT use); we gain stability for the TS4 USB tunnel and
    # the keyboard-survives-TBT-events case.
    #
    # Revert: remove this line. Verify current state with
    #   cat /sys/module/thunderbolt/parameters/host_reset   # Y or N
    #
    # Refs:
    #   - Patch (AMD): https://lists.openwall.net/linux-kernel/2023/11/22/161
    #   - Regression (Dell WD19TB, leading to the parameter):
    #     https://www.spinics.net/lists/linux-usb/msg262200.html
    #   - Framework workaround thread:
    #     https://community.frame.work/t/workaround-xhci-host-controller-not-responding-at-resume-after-suspend/79119
    "thunderbolt.host_reset=0"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7275aed4-0266-4f84-8169-246b245640f9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7275aed4-0266-4f84-8169-246b245640f9".device = "/dev/disk/by-uuid/7275aed4-0266-4f84-8169-246b245640f9";

  # Resume from hibernate — the root LUKS device contains the swap file.
  boot.resumeDevice = "/dev/mapper/luks-7275aed4-0266-4f84-8169-246b245640f9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AA80-84F8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  zramSwap = {
    enable = true;
    # 75% (≈23 GiB logical) up from the 50% default. This box runs a chronically
    # over-committed working set (Chrome + multiple GiB-scale terminals + LLM CLIs
    # + Rust builds), so it lives deep in swap. At 50% (15 GiB) zram fills and the
    # tail spills to the slow disk /swapfile (prio -1), and faulting interactive
    # threads block on that disk I/O — observed as UI lag (user.slice io.pressure
    # full ~63% during builds, while CPU full-pressure stayed 0: this is a memory,
    # not a scheduling, problem).
    #
    # memoryPercent sets the *logical (uncompressed)* device size, not a
    # compression promise. Physical RAM cost = stored ÷ ratio; at the observed
    # ~4.5:1 zstd ratio, a full 23 GiB device costs only ~5 GiB physical, which
    # comfortably holds the current ~23 GiB swapped set in RAM instead of on disk.
    #
    # Not 100%: zram (prio 5) fills before the disk swapfile, and a full device's
    # worst-case (incompressible, ~1:1) cost would consume all RAM and OOM before
    # ever spilling to disk. 75% keeps a survivable working-set floor if the ratio
    # degrades and preserves the disk swapfile as a genuine last-resort valve.
    memoryPercent = 75;
  };

  # Optimize sysctl parameters for zram swap.
  #
  # With zram, "swapping" means compressing pages in RAM rather than writing
  # to disk, so the cost/benefit tradeoffs of these tunables change significantly.
  #
  # References:
  #   - https://wiki.archlinux.org/title/Zram#Optimizing_swap_on_zram
  #   - https://docs.kernel.org/admin-guide/sysctl/vm.html
  #   - https://github.com/NixOS/nixpkgs/pull/351002
  boot.kernel.sysctl = {
    # NixOS default is 16 (remount only). Enable all SysRq functions so
    # Alt+SysRq+REISUB can recover from kernel deadlocks and hangs.
    "kernel.sysrq" = 1;
    # Default is 60. Range is 0-200 (expanded from 0-100 for zram/zswap).
    # Higher values tell the kernel to prefer compressing cold anonymous pages
    # into zram over evicting file cache. Since zram decompression (~µs) is
    # orders of magnitude faster than even NVMe reads (~100µs), this keeps
    # more hot file cache in RAM at the cost of cheap compression CPU cycles.
    "vm.swappiness" = 180;

    # Default is 15000. Controls reclaim of watermark_boost pages after an
    # external fragmentation event. Not useful with zram (no disk seek penalty
    # to amortize), and the wakeups waste power on laptops.
    "vm.watermark_boost_factor" = 0;

    # Default is 10 (0.1% of RAM). Distance between min/low/high watermarks.
    # Higher value gives kswapd more runway to reclaim in the background before
    # direct reclaim stalls occur, reducing latency spikes under pressure.
    "vm.watermark_scale_factor" = 125;

    # Default is 3 (read 2^3=8 pages at a time from swap). Swap readahead
    # helps with sequential disk access but zram has no seek penalty, so
    # readahead just wastes memory bandwidth. 0 disables it.
    "vm.page-cluster" = 0;
  };

  # Disk-backed swap for hibernate. zram handles day-to-day swapping (fast,
  # in-RAM compression) but can't persist across power-off. This file is only
  # used as the hibernate image target for suspend-then-hibernate.
  swapDevices = [{
    device = "/swapfile";
    size = 32 * 1024;  # 32 GiB (match RAM for hibernate)
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
