{ config, pkgs, lib, ... }:

{
  imports = [ ./badged.nix ];

  # Hardware-configuration.nix is generated by nixos-generate-config
  # and imported via flake.nix — don't import it here.

  # Boot
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 20;
  boot.loader.systemd-boot.consoleMode = "5";
  boot.initrd.systemd.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  networking.hostName = "wizardtower";
  networking.networkmanager.enable = true;

  # Locale
  time.timeZone = "America/Los_Angeles";
  i18n.defaultLocale = "en_US.UTF-8";

  # Niri compositor (provided by niri-flake)
  programs.niri.enable = true;
  programs.niri.package = pkgs.niri-unstable;

  # Display manager — greetd with tuigreet (lightweight, TTY-based)
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        command = "${pkgs.tuigreet}/bin/tuigreet --time --remember --remember-session --asterisks --greeting 'hack the planet' --theme 'border=magenta;text=cyan;prompt=green;time=red;action=bold;button=yellow' --cmd niri-session";
        user = "greeter";
      };
    };
  };

  # Audio — PipeWire
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
    wireplumber = {
      enable = true;
      extraConfig = {
        "51-bluez-config" = {
          "monitor.bluez.properties" = {
            # Roles the computer will advertise to Bluetooth devices.
            # Without explicit roles, some devices (e.g. Jabra Speak2 75) only get
            # HSP/HFP headset profiles and never negotiate A2DP high-quality audio.
            #
            # Enabled:
            #   a2dp_sink — send high-quality stereo audio TO a speaker/headphones (one-way)
            #   hfp_ag    — act as call audio gateway for mic+speaker (two-way, lower quality)
            #               WirePlumber auto-switches between A2DP and HFP when apps request a mic.
            #
            # Not enabled:
            #   a2dp_source — receive high-quality audio FROM a device (e.g. phone streaming to computer)
            #   hsp_hs      — computer acts as a headset for another device (obsolete, use HFP)
            #   hsp_ag      — computer acts as call gateway via HSP (obsolete, use HFP)
            #   hfp_hf      — computer acts as a hands-free device for another device's calls
            #   bsp         — LE Audio broadcast sink (needs BT 5.2+ LE Audio on both ends)
            "bluez5.roles" = [ "a2dp_sink" "hfp_ag" ];
            "bluez5.enable-sbc-xq" = true;   # better quality SBC codec variant
            "bluez5.enable-msbc" = true;      # wideband voice for HFP calls
            "bluez5.enable-hw-volume" = true;  # sync volume to device hardware
          };
        };
      };
    };
  };

  # Graphics (AMD iGPU — Ryzen AI 300 series)
  hardware.graphics.enable = true;

  # Firmware updates (Framework)
  services.fwupd.enable = true;

  # Keyboard
  services.xserver.xkb = {
    layout = "us";
    options = "caps:escape";
  };
  # Also set console keymap for TTY
  console.useXkbConfig = true;

  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-gnome ];
  };

  # Fonts
  fonts = {
    packages = with pkgs; [
      cascadia-code
      inter
      geist-font
    ];
    fontconfig.defaultFonts = {
      monospace = [ "Cascadia Code NF" ];
      sansSerif = [ "Inter" ];
      emoji = [ "Noto Color Emoji" ];
    };
  };

  # User account
  users.users.aroman = {
    isNormalUser = true;
    description = "Avi Romanoff";
    extraGroups = [ "wheel" "networkmanager" "video" "input" ];
    shell = pkgs.fish;
  };

  # Enable fish system-wide (needed for it to be a valid login shell)
  programs.fish.enable = true;

  programs.dconf.enable = true;

  # 1Password (NixOS module sets up browser extension socket + polkit)
  programs._1password.enable = true;
  programs._1password-gui = {
    enable = true;
    polkitPolicyOwners = [ "aroman" ];
  };

  # Polkit (needed by 1Password, niri, etc.)
  security.polkit.enable = true;
  # Disable niri-flake's bundled KDE polkit agent (badged replaces it)
  systemd.user.services.niri-flake-polkit.enable = false;


  security.pam.services.greetd.fprintAuth = false;

  # GNOME Keyring (for secrets, SSH agent, etc.)
  services.gnome.gnome-keyring.enable = true;

  # Battery / power info (used by ironbar, etc.)
  services.upower.enable = true;

  # Bluetooth
  hardware.bluetooth.enable = true;

  # Fan control for Framework (using default curves for now)
  # Custom curves from Silverblue backup are in NixLifeboat/fw-fanctrl-config.json
  hardware.fw-fanctrl.enable = true;

  # Allow unfree packages (Spotify, 1Password, Chrome, etc.)
  nixpkgs.config.allowUnfree = true;

  # Electron/Chromium apps: use native Wayland
  environment.sessionVariables.NIXOS_OZONE_WL = "1";
  environment.sessionVariables.QT_STYLE_OVERRIDE = "adwaita-dark";

  # Core system packages (user packages go in home.nix)
  environment.systemPackages = with pkgs; [
    git
    curl
  ];

  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    substituters = [ "https://niri.cachix.org" ];
    trusted-public-keys = [ "niri.cachix.org-1:Wv0OmO7PsuocRKzfDoJ3mulSl7Z6oezYhGhR+3W2964=" ];
  };

  # Automatic garbage collection
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  system.stateVersion = "24.11";
}
