{ config, pkgs, lib, ... }:

{
  # Hardware-configuration.nix is generated by nixos-generate-config
  # and imported via flake.nix — don't import it here.

  # Boot
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 20;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  networking.hostName = "framework";
  networking.networkmanager.enable = true;

  # Locale
  time.timeZone = "America/New_York";
  i18n.defaultLocale = "en_US.UTF-8";

  # Niri compositor (provided by niri-flake)
  programs.niri.enable = true;

  # Display manager — greetd with tuigreet (lightweight, TTY-based)
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd niri-session";
        user = "greeter";
      };
    };
  };

  # Audio — PipeWire
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    wireplumber.enable = true;
  };
  # Prevent PulseAudio from conflicting
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;

  # Graphics (AMD iGPU — Ryzen AI 300 series)
  hardware.graphics.enable = true;

  # Firmware updates (Framework)
  services.fwupd.enable = true;

  # Keyboard
  services.xserver.xkb = {
    layout = "us";
    options = "caps:escape";
  };
  # Also set console keymap for TTY
  console.useXkbConfig = true;

  # Fonts
  fonts = {
    packages = with pkgs; [
      cascadia-code
      nerd-fonts.caskaydia-cove
      noto-fonts
      noto-fonts-emoji
      inter
    ];
    fontconfig.defaultFonts = {
      monospace = [ "CaskaydiaCove Nerd Font" ];
      sansSerif = [ "Inter" ];
      emoji = [ "Noto Color Emoji" ];
    };
  };

  # User account
  users.users.aroman = {
    isNormalUser = true;
    description = "Avi Romanoff";
    extraGroups = [ "wheel" "networkmanager" "video" "input" ];
    shell = pkgs.fish;
  };

  # Enable fish system-wide (needed for it to be a valid login shell)
  programs.fish.enable = true;

  # GPG
  programs.gnupg.agent = {
    enable = true;
    pinentryPackage = pkgs.pinentry-gnome3;
  };

  # Polkit (needed by 1Password, niri, etc.)
  security.polkit.enable = true;

  # GNOME Keyring (for secrets, SSH agent, etc.)
  services.gnome.gnome-keyring.enable = true;

  # Portal (xdg-desktop-portal for screen sharing, file picker, etc.)
  # niri-flake sets up portals, but ensure GNOME portal is available for GTK apps
  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-gnome ];
  };

  # Dark mode for GTK apps
  environment.sessionVariables = {
    # Tell GTK apps to use dark theme
    GTK_THEME = "Adwaita:dark";
  };

  # Power management (recommended for Framework AMD by nixos-hardware)
  services.power-profiles-daemon.enable = true;

  # Bluetooth
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # Fan control for Framework (using default curves for now)
  # Custom curves from Silverblue backup are in NixLifeboat/fw-fanctrl-config.json
  hardware.fw-fanctrl.enable = true;

  # Allow unfree packages (Spotify, 1Password, Chrome, etc.)
  nixpkgs.config.allowUnfree = true;

  # Core system packages (user packages go in home.nix)
  environment.systemPackages = with pkgs; [
    vim
    git
    wget
    curl
  ];

  # Enable Nix flakes
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Automatic garbage collection
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  system.stateVersion = "24.11";
}
