# Do not modify this file!  It was generated by ‘nixos-generate-config’
# t
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [
    "amdgpu.cwsr_enable=0"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7275aed4-0266-4f84-8169-246b245640f9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7275aed4-0266-4f84-8169-246b245640f9".device = "/dev/disk/by-uuid/7275aed4-0266-4f84-8169-246b245640f9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AA80-84F8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  zramSwap = {
    enable = true;
    memoryPercent = 50;
  };

  # Optimize sysctl parameters for zram swap.
  #
  # With zram, "swapping" means compressing pages in RAM rather than writing
  # to disk, so the cost/benefit tradeoffs of these tunables change significantly.
  #
  # References:
  #   - https://wiki.archlinux.org/title/Zram#Optimizing_swap_on_zram
  #   - https://docs.kernel.org/admin-guide/sysctl/vm.html
  #   - https://github.com/NixOS/nixpkgs/pull/351002
  boot.kernel.sysctl = {
    # NixOS default is 16 (remount only). Enable all SysRq functions so
    # Alt+SysRq+REISUB can recover from kernel deadlocks and hangs.
    "kernel.sysrq" = 1;
    # Default is 60. Range is 0-200 (expanded from 0-100 for zram/zswap).
    # Higher values tell the kernel to prefer compressing cold anonymous pages
    # into zram over evicting file cache. Since zram decompression (~µs) is
    # orders of magnitude faster than even NVMe reads (~100µs), this keeps
    # more hot file cache in RAM at the cost of cheap compression CPU cycles.
    "vm.swappiness" = 180;

    # Default is 15000. Controls reclaim of watermark_boost pages after an
    # external fragmentation event. Not useful with zram (no disk seek penalty
    # to amortize), and the wakeups waste power on laptops.
    "vm.watermark_boost_factor" = 0;

    # Default is 10 (0.1% of RAM). Distance between min/low/high watermarks.
    # Higher value gives kswapd more runway to reclaim in the background before
    # direct reclaim stalls occur, reducing latency spikes under pressure.
    "vm.watermark_scale_factor" = 125;

    # Default is 3 (read 2^3=8 pages at a time from swap). Swap readahead
    # helps with sequential disk access but zram has no seek penalty, so
    # readahead just wastes memory bandwidth. 0 disables it.
    "vm.page-cluster" = 0;
  };

  # swapDevices =
  #   # [ { device = "/dev/mapper/luks-b7920935-338b-4495-aafc-0e112de2cf4d"; }
  #   ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
