# Do not modify this file!  It was generated by ‘nixos-generate-config’
# t
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [
    "amdgpu.cwsr_enable=0"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7275aed4-0266-4f84-8169-246b245640f9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7275aed4-0266-4f84-8169-246b245640f9".device = "/dev/disk/by-uuid/7275aed4-0266-4f84-8169-246b245640f9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AA80-84F8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  zramSwap = {
    enable = true;
    memoryPercent = 50;
  };

  # swapDevices =
  #   # [ { device = "/dev/mapper/luks-b7920935-338b-4495-aafc-0e112de2cf4d"; }
  #   ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
